---
#---------------------------
# Timezone
#---------------------------

system_time_zone : Australia/Sydney


#---------------------------
# fail2ban
#---------------------------

fail2ban_log_level: 3
fail2ban_log_file : /var/log/fail2ban.log
fail2ban_destemail: getintouch@icomefromthenet.com
fail2ban_ignoreip : 127.0.0.1