---
# install and configure apache_mod_security

 - name: Apache | Install libxml dependecies
   action: apt pkg=$item state=installed
   with_items:
    - libxml2
    - libxml2-dev 
    - libxml2-utils
    
 - name: Apache | Install arpu dependecies
   action: apt pkg=$item state=installed
   with_items:
    - libaprutil1
    - libaprutil1-dev
        
 - name: Apache | Install mod_security from repo
   action: apt pkg=libapache-mod-security state=installed
   notify:
    - restart apache
        
 - name: Apache | Copy OWSAP rule set from sourceforge
   action: copy src=../files/${apache_mod_security_release}.tar.gz dest=/var/tmp/${apache_mod_security_release}.tar.gz 
   
 - name: Apache | Uncompress the rule-set
   action: command sudo /bin/tar xz -f /var/tmp/${apache_mod_security_release}.tar.gz -C /etc/apache2/ 
 
 - name: Apache | Remove existing ruleset directory
   action: file path=/etc/apache2/modsecurity-crs state=absent
   
 - name: Apache | Rename ruleset directory
   action: command mv -f /etc/apache2/${apache_mod_security_release} /etc/apache2/modsecurity-crs creates=/etc/apache2/modsecurity-crs
   
 - name: Apache | Rename the OWSAP rule config file
   action: command mv /etc/apache2/modsecurity-crs/modsecurity_crs_10_setup.conf.example /etc/apache2/modsecurity-crs/modsecurity_crs_10_config.conf creates=/etc/apache2/modsecurity-crs/modsecurity_crs_10_config.conf
   notify:
    - restart apache
    
 - name: Apache | Copy activate rules script to server
   action: copy src=../files/activate_rules.sh dest=/etc/apache2/modsecurity-crs/activate_rules.sh mode=0755 
   
 - name: Apache | Run activate rules script  
   action: command sudo /etc/apache2/modsecurity-crs/activate_rules.sh
   notify:
    - restart apache
    
 - name: Apache | Remove activate rules script
   action: file path=/etc/apache2/modsecurity-crs/activate_rules.sh state=absent

    