---
# install code to develop pear extensions

 - name: PHP PEAR Dev | Upgrade pear
   action: command /usr/bin/pear upgrade PEAR
 
 - name: PHP PEAR Dev | Pear to use stable packages
   action: command /usr/bin/pear config-set preferred_state stable
   
 - name: PHP PEAR Dev | Discover prium pear channel
   action : command /usr/bin/pear channel-discover pear.pirum-project.org
   ignore_errors: True
   
 - name: PHP PEAR Dev | Install XML Serializer
   action: command /usr/bin/pear -d preferred_state=alpha install XML_Serializer
   ignore_errors: True

 - name: PHP PEAR Dev | Install PEAR PackageFileManager2
   action: command /usr/bin/pear install PEAR_PackageFileManager2
   ignore_errors: True
   
 - name: PHP PEAR Dev | Install prium
   action: command /usr/bin/pear install pirum/Pirum
   ignore_errors: True