---
# secure mysql
 
 - name: MySQL | Set the root password.
   action: mysql_user user=root password=$mysql_password host=localhost
   tags: database

 - name: MySQL | Config for easy access for root user
   action: template src="templates/root-my-cnf.j2" dest="/root/.my.cnf"
   tags: database
   notify:
    - restart mysql 
 
 - name: MySQL | Delete anonymous MySQL server user for localhost
   action: mysql_user user="" state="absent" 
   tags: database
  
 - name: MySQL | Secure the MySQL root user for IPV6 localhost (::1)
   action: mysql_user name="root" password="$mysql_password" host="::1" state="present"
   tags: database

 - name: MySQL | Secure the MySQL root user for IPV4 localhost (127.0.0.1)
   action: mysql_user name="root" password="$mysql_password" host="127.0.0.1" state="present"
   tags: database

 - name: MySQL | Secure the MySQL root user for localhost domain (localhost)
   action: mysql_user name="root" password="$mysql_password" host="localhost" state="present"
   tags: database

 - name: MySQL | Secure the MySQL root user for server_hostname domain
   action: mysql_user name="root" password="$mysql_password" host="$inventory_hostname" state="present"
   tags: database

 - name: MySQL | Remove the MySQL test database
   action: mysql_db login_user="root" login_password="$mysql_password" db=test state="absent"
   tags: database    
 